name: juneau
description: juneau mobile application
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  edge_alert: ^0.0.1
  email_validator: ^1.0.0
  flutter_absolute_path: ^1.0.6
  http: ^0.12.0+4
  multi_image_picker: ^4.7.10
  path: ^1.7.0
  pull_to_refresh: ^1.6.1
  shared_preferences: ^0.5.8
  timeago: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/

  fonts:
    - family: Lato Black
      fonts:
      - asset: fonts/Lato-Black.ttf
    - family: Lato Regular
      fonts:
      - asset: fonts/Lato-Regular.ttf