name: juneau
description: juneau mobile application
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  dots_indicator: ^1.2.0
  edge_alert: ^0.0.1
  email_validator: ^1.0.0
  flutter_absolute_path: ^1.0.6
  flutter_swipe_action_cell: ^1.2.2
  http: ^0.12.0+4
  keyboard_visibility: ^0.5.6
  multi_image_picker: ^4.7.10
  path: ^1.7.0
  pull_to_refresh: ^1.6.1
  rxdart: ^0.24.1
  scrollable_positioned_list: ^0.1.8
  shared_preferences: ^0.5.8
  timeago: ^2.0.26

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/